name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Commands
        run: |
          ls       # List files in the current directory
          pwd      # Print the current working directory
          whoami   # Print the current user
    # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
