name: Test Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t flask-image .

    - name: Run Docker container using image
      run: docker run -d --name flask-container -p 5000:5000 flask-image

    - name: Wait for the service to be ready
      run: sleep 30s

    - name: Get flask-container container logs
      run: docker logs flask-container

    - name: Test API
      run: curl http://localhost:5000

    - name: Get flask-container container logs
      run: docker logs flask-container


