name: Test Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker image
      run: |
        cd Flask-image
        docker build -t flask-image .

    - name: Run docker container using image
      run: |
        docker run -it --name flask-container -p 5000:5000 flask-image
